
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E345B0502379CE9E5385BCB7B5013CD3'
    
_lr_action_items = {'DCL':([0,1,2,4,5,],[2,2,-4,-2,-3,]),'$end':([1,2,3,4,5,],[-1,-4,0,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement_list':([0,],[1,]),'program':([0,],[3,]),'statement':([0,1,],[4,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','lyayacc.py',12),
  ('statement_list -> statement','statement_list',1,'p_statement_list','lyayacc.py',16),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','lyayacc.py',17),
  ('statement -> DCL','statement',1,'p_statement','lyayacc.py',22),
  ('lower_bound -> integer_literal','lower_bound',1,'p_lower_bound','lyayacc.py',142),
  ('integer_literal -> digit_sequence','integer_literal',1,'p_integer_literal','lyayacc.py',146),
  ('digit_sequence -> ICONST','digit_sequence',1,'p_digit_sequence','lyayacc.py',150),
  ('digit_sequence -> USCORE','digit_sequence',1,'p_digit_sequence','lyayacc.py',151),
  ('digit_sequence -> digit_sequence ICONST','digit_sequence',2,'p_digit_sequence','lyayacc.py',152),
  ('digit_sequence -> digit_sequence USCORE','digit_sequence',2,'p_digit_sequence','lyayacc.py',153),
]
